name: 'Hello World'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'

jobs:

  hello:

    runs-on: ubuntu:latest

    steps:
      - name: hello-world
        run: echo ${{ inputs.who-to-greet  }}
