name: 'Hello World'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v3
      - name: docker-build
        run: docker build -t teste .
    
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - run: go version
